on:
  push:
  pull_request:

name: ğŸ—ï¸ Build

jobs:
  build-fedora37:
    runs-on: ubuntu-latest
    container: fedora:37

    steps:
      - name: ğŸ“¥ Checkout
        uses: actions/checkout@v3

      - name: ğŸ‘· Build Dependencies
        run: |
          dnf install -y make automake gcc gcc-c++ kernel-devel cmake git
          dnf install -y pipewire-devel pipewire-libs pulseaudio-libs-devel pipewire-pulseaudio

      - name: ğŸ”¨ Build Server
        run: |
          cmake -B build
          cmake --build build

      - name: ğŸš€ Upload Server
        uses: actions/upload-artifact@v3
        with:
          name: server-x86-64
          path: build/server

      - name: ğŸƒ Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: ğŸƒ Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false

      - name: ğŸ”¨ Build Addon
        run: |
          rm -rf build
          pnpm install

      - name: ğŸš€ Upload Addon
        uses: actions/upload-artifact@v3
        with:
          name: addon-x86-64
          path: build/Release

  build-fedora37-arm:
    runs-on: ubuntu-latest
    container: arm64v8/fedora:37

    steps:
      - name: ğŸ“¥ Checkout
        uses: actions/checkout@v3

      - name: ğŸ‘· Build Dependencies
        run: |
          dnf install -y make automake gcc gcc-c++ kernel-devel cmake git
          dnf install -y pipewire-devel pipewire-libs pulseaudio-libs-devel pipewire-pulseaudio

      - name: ğŸ”¨ Build Server
        run: |
          cmake -B build
          cmake --build build

      - name: ğŸš€ Upload Server
        uses: actions/upload-artifact@v3
        with:
          name: server-armv8
          path: build/server

      - name: ğŸƒ Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: ğŸƒ Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false

      - name: ğŸ”¨ Build Addon
        run: |
          rm -rf build
          pnpm install

      - name: ğŸš€ Upload Addon
        uses: actions/upload-artifact@v3
        with:
          name: addon-armv8
          path: build/Release
