on:
  push:
  pull_request:

name: ğŸ—ï¸ Build

jobs:
  build-arch-server:
    runs-on: ubuntu-latest
    container: archlinux:base-devel

    steps:
      - name: ğŸ“¥ Checkout
        uses: actions/checkout@v3

      - name: ğŸ”¨ Build
        run: |
          cmake -B build
          cmake --build build

      - name: ğŸš€ Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: server
          path: build/server

  build-arch-addon:
    runs-on: ubuntu-latest
    container: archlinux:base-devel

    steps:
      - name: ğŸ“¥ Checkout
        uses: actions/checkout@v3

      - name: ğŸ”¨ Build
        run: |
          pnpm install

      - name: ğŸš€ Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: addon
          path: build/Release

  build-fedora-server:
    runs-on: ubuntu-latest
    container: fedora:latest

    steps:
      - name: ğŸ“¥ Checkout
        uses: actions/checkout@v3

      - name: ğŸ”¨ Build
        run: |
          cmake -B build
          cmake --build build

      - name: ğŸš€ Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: server
          path: build/server

  build-fedora-addon:
    runs-on: ubuntu-latest
    container: fedora:latest

    steps:
      - name: ğŸ“¥ Checkout
        uses: actions/checkout@v3

      - name: ğŸ”¨ Build
        run: |
          pnpm install

      - name: ğŸš€ Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: addon
          path: build/Release
